### PR TITLE
Fix#4

### PR DESCRIPTION
**Pull request by luan-cestari**
https://github.com/lightblue-platform/lightblue-docs-overview/issues/4

### CODE REVIEW

**Comment by jewzaam** [comment]
@derek63 could you review to check that the update explains `joins` sufficiently?

**Comment by jewzaam** [comment]
Fixes https://github.com/lightblue-platform/lightblue-docs-overview/issues/4

**Comment by derek63** [comment]
@luan-cestari The updates to this look good, but the PR can't be automatically merged.  Please make the necessary updates for a clean merge whenever you have the chance.

**Comment by jewzaam** [comment]
@derek63 @luan-cestari this can't be merged because this was moved to another repo.
Closing this and have opened https://github.com/lightblue-platform/lightblue-docs-specs/pull/9 for merging to the specs repo.

**Pull request closed without merging**
