### PR TITLE
Added security section

### PR DESCRIPTION
**Pull request by jewzaam**

### CODE REVIEW

**Comment by derek63** [comment]
@jewzaam This looks really good overall.  Should we add references to the Picketlink project to explain how we're implementing SAML integration?

**Comment by jewzaam** [comment]
Sure.  Maybe merge this (if you think it's ready) and then put in another PR with that?

**Comment by derek63** [comment]
Okay will do, merging now

**Comment by derek63** [comment]
Added Picketlink references in https://github.com/lightblue-platform/lightblue-docs-user/pull/73

**Pull request merged**
